# Generated by Django 5.1.2 on 2024-11-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_1', models.ImageField(upload_to='')),
                ('i_2', models.ImageField(upload_to='')),
            ],
        ),
    ]
